SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# 3.2
PLAYER_RADIUS = 20
LINE_WIDTH = 2 # width of the line that draw the player ship

# 3.3
PLAYER_TURN_SPEED = 300

# 3.4
PLAYER_SPEED = 200

# 4.1
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS